### ISSUE TITLE
阅读计划

### ISSUE THREAD

**Issue by heicx** [heicx/ReadPlan#1]
每本书限额人数最多4个人。
阅读计划针对有一定基础的开发人员，重点在与回顾总结，加强记忆点。
选择你要协同阅读的书名。如果对所列的书有异议，欢迎QQ与我商讨。

QQ 200894178 或者 群内

**Comment by myopensrc** [comment]
js高级程序设计第三版 简单

**Comment by zhixinyiye** [comment]
css权威指南

**Comment by Ellacf** [comment]
js高级程序设计第三版

**Comment by QAQMiao** [comment]
js高级程序设计第三版

**Comment by QAQMiao** [comment]
喵喵

**Comment by Liu-Young** [comment]
js高级程序设计第三版.  @果地

**Comment by AntiMoron** [comment]
js高级程序设计第三版   杭州-AntiMoron   想要和喵喵一组。QAQ

**Comment by AntiMoron** [comment]
css权威指南   杭州~AntiMoron

**Comment by AntiMoron** [comment]
javascript权威指南  杭州AntiMoron

**Comment by heicx** [comment]
> 二期
- [ ] 编写高质量代码 改善JavaScript程序的188个建议
